baseURL        = "https://leonardonzio.github.io/iss2026-cargoservice/"
title          = "ISS 2026 - Cargo Service"
locale         = "it-IT"
theme          = "chicago7"
enableEmoji    = true

pagination.pagerSize = 10

[permalinks]
posts = "/posts/:year:month:day"

[markup]
  [markup.goldmark.renderer]
    unsafe = true # raw HTML in markdown

  [markup.highlight]
    style = "bw"

  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 4
    ordered    = false

# Navigation menu
[menu]
[[menu.header]]
name   = "Sprint0"
url    = "sprint0"
weight = 10

[[menu.header]]
name   = "Sprint1"
url    = "sprint1"
weight = 20

# Site parameters
[params]
logo = "logo.svg" # relative patwh inside static/
author = "Leonardo Barone, Leonardo Ciacco"
subtitle = "Ingegneria dei Sistemi Software 2026 - Cargo Service"
missingContentMessage = "Pagina non trovata." # 404
math = true # default every page have katex

[params.social]
github = "https://github.com/leonardonzio/iss2026-cargoservice/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
