baseURL        = "https://leonardonzio.github.io/iss2026-cargoservice/"
title          = "ISS 2026 - Cargo Service"
locale         = "it-IT"
theme          = "chicago7"
enableEmoji    = true

pagination.pagerSize = 10

[permalinks]
posts = "/posts/:year:month:day"

[markup]
  [markup.goldmark.renderer]
    unsafe = true # raw HTML in markdown

  [markup.highlight]
    style = "bw"

  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 4
    ordered    = false


[params]
subtitle = "Ingegneria dei Sistemi Software 2026 - Cargo Service"
missingContentMessage = "Pagina non trovata." # 404
math = true # default every page have katex
logo = "emojimarines.png" # relative path inside static/

[[params.authors]]
name  = "Leonardo Barone"
email = "leonardo.barone3@studio.unibo.it"
img   = "cargoemoji.jpg"   # relative to static/

[[params.authors]]
name  = "Leonardo Ciacco"
email = "leonardo.ciacco@studio.unibo.it"
img   = "cargoemoji2.jpg"

[[params.authors]]
name  = "Andrei Cezar Radu"
email = "andrei.radu@studio.unibo.it"
img   = "cargoship.jpeg"


[params.social]
github = "https://github.com/leonardonzio/iss2026-cargoservice/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
